[build]
  command = "npm run export"
  functions = "functions"
  publish = "__sapper__"

[[redirects]]
  from = "/disqus/*"
  to = "https://disqus.com/api/3.0/forums/:splat"
  status = 200
  force = true